-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 00:40:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MEIDATA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MEIDATA` ;

-- -----------------------------------------------------
-- Schema MEIDATA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MEIDATA` DEFAULT CHARACTER SET utf8 ;
USE `MEIDATA` ;

-- -----------------------------------------------------
-- Table `MEIDATA`.`TipoDeDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`TipoDeDocumento` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`TipoDeDocumento` (
  `idTipoDeDocumento` INT NOT NULL,
  `Documento` ENUM('CC', 'NIT', 'PA') NULL,
  PRIMARY KEY (`idTipoDeDocumento`),
  UNIQUE INDEX `Documento_UNIQUE` (`Documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Roles` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Roles` (
  `idRoles` INT NOT NULL,
  `Roll` ENUM('ADMIN,STAFF,OTRO') NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Registros` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Registros` (
  `idUsuario` VARCHAR(50) NOT NULL,
  `Contraseña` SMALLINT(8) NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Registros_Roles1_idx` (`Roles_idRoles` ASC) VISIBLE,
  CONSTRAINT `fk_Registros_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `MEIDATA`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Barrios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Barrios` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Barrios` (
  `idBarrios` INT NOT NULL,
  `Barrio` ENUM('CHAPINERO,USME,MIRAMAR,CANDIDO,POBLADO,BELEN') NOT NULL,
  PRIMARY KEY (`idBarrios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `Ciudad` ENUM('BOGATA,NEIVA,MEDELLIN') NOT NULL,
  `Barrios_idBarrios` INT NOT NULL,
  PRIMARY KEY (`idCiudad`, `Barrios_idBarrios`),
  INDEX `fk_Ciudad_Barrios1_idx` (`Barrios_idBarrios` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Barrios1`
    FOREIGN KEY (`Barrios_idBarrios`)
    REFERENCES `MEIDATA`.`Barrios` (`idBarrios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Departamento` ENUM('CUNDINAMARTCA,HUILA,ANTIOQUIA') NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`, `Ciudad_idCiudad`),
  INDEX `fk_Departamento_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `MEIDATA`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `Calle` INT(3) UNSIGNED NULL,
  `ComplementoCalle` ENUM('A,B,C,D,E,F,G,H,I,J,Q,K,L,M,O,P,R,S,T,V,W,X,Y,Z') NULL,
  `Carrera` INT(3) NULL,
  `complementocarrera` ENUM('A,B,C,D,E,F,G,H,I,J,Q,K,L,M,O,P,R,S,T,V,W,X,Y,Z') NULL,
  `NumeroDir1` VARCHAR(45) NULL,
  `NumeroDir2` VARCHAR(45) NULL,
  `Transversal` INT(3) NULL,
  `Diagonal` INT(3) NULL,
  `Residencia` VARCHAR(30) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Direccioncol` ENUM('NORTE,SUR,ORIENTE,OCCIDENTE,SUR ORIENTE,NOR ORIENTE,SUR OCCIDENTE, NOR OCCIDENTE') NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Departamento_Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idDireccion`, `Departamento_idDepartamento`, `Departamento_Ciudad_idCiudad`),
  INDEX `fk_Direccion_Departamento1_idx` (`Departamento_idDepartamento` ASC, `Departamento_Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento` , `Departamento_Ciudad_idCiudad`)
    REFERENCES `MEIDATA`.`Departamento` (`idDepartamento` , `Ciudad_idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `RazonSocial` VARCHAR(250) NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `RazonSocila_UNIQUE` (`RazonSocial` ASC) VISIBLE,
  INDEX `fk_Empresa_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `MEIDATA`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`CategoriaUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`CategoriaUsuario` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`CategoriaUsuario` (
  `idCategoriaUsuario` INT NOT NULL AUTO_INCREMENT,
  `Categorias` ENUM('CLIENTE,TRABAJADOR,PROVEEDOR') NOT NULL,
  PRIMARY KEY (`idCategoriaUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Usuarios` (
  `idPersonas` INT UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `SegundoNombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Personascol` VARCHAR(45) NULL,
  `FKTipoDeDocumento` INT NOT NULL,
  `Registros_idUsuario` VARCHAR(50) NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Empresa_idDireccion` INT NOT NULL,
  `CategoriaUsuario_idCategoriaUsuario` INT NOT NULL,
  PRIMARY KEY (`idPersonas`),
  INDEX `fk_Personas_TipoDeDocumento_idx` (`FKTipoDeDocumento` ASC) VISIBLE,
  INDEX `fk_Usuarios_Registros1_idx` (`Registros_idUsuario` ASC) VISIBLE,
  INDEX `fk_Usuarios_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  INDEX `fk_Usuarios_Empresa2_idx` (`Empresa_idDireccion` ASC) VISIBLE,
  INDEX `fk_Usuarios_CategoriaUsuario1_idx` (`CategoriaUsuario_idCategoriaUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_TipoDeDocumento`
    FOREIGN KEY (`FKTipoDeDocumento`)
    REFERENCES `MEIDATA`.`TipoDeDocumento` (`idTipoDeDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Registros1`
    FOREIGN KEY (`Registros_idUsuario`)
    REFERENCES `MEIDATA`.`Registros` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `MEIDATA`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Empresa2`
    FOREIGN KEY (`Empresa_idDireccion`)
    REFERENCES `MEIDATA`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_CategoriaUsuario1`
    FOREIGN KEY (`CategoriaUsuario_idCategoriaUsuario`)
    REFERENCES `MEIDATA`.`CategoriaUsuario` (`idCategoriaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Productos` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Productos` (
  `idProductos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  `Codigo` INT UNSIGNED NOT NULL,
  `Precio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Factura` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Factura` (
  `NumeroFactura` INT UNSIGNED NOT NULL,
  `Fecha` DATETIME(2) NOT NULL,
  `Detalle` TEXT(250) NULL,
  `Usuarios_idPersonas` INT UNSIGNED NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`NumeroFactura`),
  UNIQUE INDEX `NumeroFactura_UNIQUE` (`NumeroFactura` ASC) VISIBLE,
  INDEX `fk_Factura_Usuarios1_idx` (`Usuarios_idPersonas` ASC) VISIBLE,
  INDEX `fk_Factura_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Usuarios1`
    FOREIGN KEY (`Usuarios_idPersonas`)
    REFERENCES `MEIDATA`.`Usuarios` (`idPersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `MEIDATA`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Compras` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Compras` (
  `Productos_idProductos` INT UNSIGNED NOT NULL,
  `Factura_NumeroFactura` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Factura_NumeroFactura`),
  INDEX `fk_Productos_has_Factura_Factura1_idx` (`Factura_NumeroFactura` ASC) VISIBLE,
  INDEX `fk_Productos_has_Factura_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Factura_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `MEIDATA`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Factura_Factura1`
    FOREIGN KEY (`Factura_NumeroFactura`)
    REFERENCES `MEIDATA`.`Factura` (`NumeroFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MEIDATA`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEIDATA`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `MEIDATA`.`Ventas` (
  `Factura_NumeroFactura` INT UNSIGNED NOT NULL,
  `Productos_idProductos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Factura_NumeroFactura`, `Productos_idProductos`),
  INDEX `fk_Factura_has_Productos_Productos1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_Factura_has_Productos_Factura1_idx` (`Factura_NumeroFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_has_Productos_Factura1`
    FOREIGN KEY (`Factura_NumeroFactura`)
    REFERENCES `MEIDATA`.`Factura` (`NumeroFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `MEIDATA`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
